// angular-ystemandchess-old/src/app/pages/puzzles/puzzles.component.ts
import { Component, OnInit } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { PuzzlesService } from 'src/app/services/puzzles/puzzles.service';
import { Chess } from 'src/app/models/Chess';
import { environment } from 'src/environments/environment';
import { setPermissionLevel } from '../../globals';
import { CookieService } from 'ngx-cookie-service';
import Swal from 'sweetalert2';

@Component({
    selector: 'app-puzzles',
    templateUrl: './puzzles.component.html',
    styleUrls: ['./puzzles.component.scss'],
})
export class PuzzlesComponent implements OnInit{
    chess;
    chessSrc;
    info = "Welcome to puzzles"
    currentFen;
    prevFen; // used to rollback on incorrect player moves
    moveList;
    themeList;
    playerColor;
    playerMove = []; // used to check player move against the correct move
    prevMove = []; // used to rollback highlights for the previous computer move
    public dbIndex=0;
    
    activeState = {
      "PuzzleId":"YzaYa",
      "FEN":"2kr3r/1pp2ppp/p1pb1n2/4q3/NPP1P3/P2P1P1P/5P2/R1BQ1RK1 w - - 1 16",
      "Moves":"d3d4 e5h2",
      "Rating":910,
      "RatingDeviation":76,
      "Popularity":96,
      "NbPlays":128,
      "Themes":"mate mateIn1 middlegame oneMove",
      "GameUrl":"https://lichess.org/nPeulvcd#31"
    };

    constructor(private ps: PuzzlesService, private sanitization: DomSanitizer) { 
	    this.chessSrc = this.sanitization.bypassSecurityTrustResourceUrl(
            environment.urls.chessClientURL
          );
          this.chess = new Chess('chessBoard', true);
	//   this.loadLessons();
    }

    ngOnInit(): void {
      // bug: for some reason the rest of the code doesn't wait for initPuzzleArray to finish before running
      // this is why the list of puzzles are still there in the service file, we're using them as initial puzzles (list of first possible puzzle)
      // by the time users get to their second puzzle, the full puzzle array should have finished loading, and everything should work as intended
      this.initPuzzleArray();
      this.shuffleArray(this.ps.puzzleArray);

      console.log("settiing state active: " + this.ps.puzzleArray[0])

      this.setStateAsActive(this.ps.puzzleArray[0]);
      this.activeState = this.ps.puzzleArray[0];
      // getting the move list and theme list of the puzzle when we start up
      this.moveList = this.activeState.Moves.split(" ");
      this.themeList = this.activeState.Themes.split(" ");
      this.updateInfoBox();

      // get elements
	    const newPuzzle = document.getElementById('newPuzzle') as HTMLElement;
      const openDialog = document.getElementById('openDialog') as HTMLElement;
      const closeDialog = document.getElementById('closeDialog') as HTMLElement;
      
      // add event listener to buttons
	    newPuzzle.addEventListener('click', () => { 

        console.log("getting new puzzle...")

        this.dbIndex = this.dbIndex+1;
        // loop back to start if we reached the end of the array
        if (this.dbIndex==this.ps.puzzleArray.length){
          this.dbIndex=0;	
        }
        this.setStateAsActive(this.ps.puzzleArray[this.dbIndex]);
        this.activeState = this.ps.puzzleArray[this.dbIndex];
        // getting the move list and theme list of the puzzle whenever we update the active state
        this.moveList = this.activeState.Moves.split(" ");
        this.themeList = this.activeState.Themes.split(" ");
        this.updateInfoBox();
	 	  });

      openDialog.addEventListener('click', () => this.openDialog());
      closeDialog.addEventListener('click', () => this.closeDialog());


      // Listen to message from child window, originally from play-nolog.component.ts, adjusted
      var eventMethod = window.addEventListener ? 'addEventListener' : 'attachEvent';
      var eventer = window[eventMethod];
      var messageEvent = eventMethod == 'attachEvent' ? 'onmessage' : 'message';
      eventer(
        messageEvent,
        (e) => {
          // print out event e
          console.log('e: ', e);
          // store the data as info
          let info = e.data;

          if (info[0] === "{"){
            let jsonInfo = JSON.parse(info)

            // store the move info if it was a player move
            if ("from" in jsonInfo && "to" in jsonInfo){
              this.playerMove[0] = jsonInfo.from;
              this.playerMove[1] = jsonInfo.to;
            }
          }

          // if it exists and is not an object
          if (info && typeof info !== "object"){
            if (this.isFen(info)){
              this.prevFen = this.currentFen;
              // update the current FEN and color
              this.currentFen = info;
            
              // get the chessBoard
              var chessBoard = (<HTMLFrameElement>(
                document.getElementById('chessBoard')
              )).contentWindow;

              // post the new FEN and color so board is updated
              // note that we are posting the message to the chessClient
              chessBoard.postMessage(
                JSON.stringify({
                  boardState: this.currentFen
                }),
                environment.urls.chessClientURL
              );
            }

            // if the user have just moved, the computer should move
            // check if it is the computer's move
            var activeColor = this.currentFen.split(" ")[1];

            // make sure that activeColor actually exists (not undefined)
            // otherwise we would be incorrectly calling shift() on moveList
            if (activeColor && activeColor !== this.playerColor){
              
              // before the computer moves, first check if the user's move was correct
              var move = this.getMove();
              if (move[0] !== this.playerMove[0] || move[1] !== this.playerMove[1]){

                // if the move doesn't match, revert the move, add the move back to move list
                this.moveList.unshift(move[0] + move[1]);

                // reset the fen to previous fen and post message
                this.currentFen = this.prevFen;
                chessBoard.postMessage(
                  JSON.stringify({
                    boardState: this.currentFen
                  }),
                  environment.urls.chessClientURL
                );
                
                // since we reverted the board state, we also need to revert the highlight
                chessBoard.postMessage(
                  JSON.stringify({
                    highlightFrom: this.prevMove[0],
                    highlightTo: this.prevMove[1]
                  }),
                  environment.urls.chessClientURL
                );

              }
              else{
                // if the user move is valid
                // first check if we're at the end of puzzle
                if (this.moveList.length == 0){
                  // if we're at the end, send a pop up to notify user that puzzle is completed
                  setTimeout(() => {
                    Swal.fire('Puzzle completed', 'Good Job', 'success').then(                  
                      // clicking ok on the pop up will simulate a click on the "Get New Puzzle" button
                      function(){
                        const button = document.getElementById('newPuzzle') as HTMLElement;
                        button.click();
                      }
                    );
                  }, 200);
                }
                else{
                  // if we're not at the end, computer should move
                  // get the move and parse it into useable form
                  var move = this.getMove();
                  var moveFrom = move[0];
                  var moveTo = move[1];
                  
                  // the computer just moved, update prevMove
                  this.prevMove[0] = move[0];
                  this.prevMove[1] = move[1];
                  
                  setTimeout(() => {
                    chessBoard.postMessage(
                      JSON.stringify({
                        from: moveFrom,
                        to: moveTo
                      }),
                      environment.urls.chessClientURL
                    );
                  }, 500);
                }
              }
            }
          }
        }
      )
    }
    
    initPuzzleArray(){
        this.httpGetAsync(
          `${environment.urls.middlewareURL}/puzzles/list`,
          'GET',
          (response) => {
            var response = JSON.parse(response);
            var jsonData = []
            for (var i = 0; i < response.length; i++) {
              jsonData.push(response[i]);
            }
            this.ps.puzzleArray = jsonData;
            this.shuffleArray(this.ps.puzzleArray);
          }
        )
        
    }

    private httpGetAsync(theUrl: string, method: string = 'POST', callback) {
      var xmlHttp = new XMLHttpRequest();
      xmlHttp.onreadystatechange = function () {
        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
          callback(xmlHttp.responseText);
      };
      xmlHttp.open(method, theUrl, true); // true for asynchronous
      xmlHttp.send(null);
    }

    openDialog() {
      //console.log("open dialog clicked");
      //const dialog = document.getElementById('myDialog') as HTMLDialogElement;
      //dialog.open = true;
      // dialog.showModal();
      var hintText = document.getElementById('hint-text');
      if (hintText.style.display === "block") {
        document.getElementById('hint-text').style.display = "none";
      }
      else {
        document.getElementById('hint-text').style.display = "block";
      }
    }
  
    closeDialog() {
      const dialog = document.getElementById('myDialog') as HTMLDialogElement;
      dialog.close();
    } 

    setStateAsActive(state) {
        console.log("click state---->", state)
        this.playerColor = state.FEN.split(" ")[1];

        var firstObj = {
          'theme': state.Themes,
          'fen': state.FEN,
          'event':''
        };
        console.log("first obj---->", firstObj)

        setTimeout(() => {
          // this.chess.newGameInit(state.fen);
          this.activeState = state;
          this.startLesson(firstObj);
        }, 500);
    }

    refresh() {
      this.chess.newGameInit(this.currentFen);
    }

    startLesson({ theme, fen, event }): void {
      console.log("start lesson call---->", theme)
      this.info = this.info;

      var color;
      // this is backwards because the first move is the computer's
      // so if the active color is black, then player is white, and vice versa
      if (this.playerColor === "b"){
        this.playerColor = "w";
        color = "white";
      }
      else{
        this.playerColor = 'b';
        color = "black";
      }

      this.chess.newGameInit(fen, color);
      this.currentFen = fen;

      // testing: trying to get a piece to move by itself
      // get the chessBoard
      var chessBoard = (<HTMLFrameElement>(
        document.getElementById('chessBoard')
      )).contentWindow;
          
      // get the first move from the list
      var move = this.getMove();
      var firstMoveFrom = move[0];
      var firstMoveTo = move[1];

      // the computer just moved, update prevMove
      this.prevMove[0] = move[0];
      this.prevMove[1] = move[1];
          
      setTimeout(() => {
        chessBoard.postMessage(
          JSON.stringify({
            from: firstMoveFrom,
            to: firstMoveTo
          }),
          environment.urls.chessClientURL
        );
      }, 500)

    }

    getMove() {
      // get the first move from the list
      var move = this.moveList.shift();
      // from: first two characters of a move
      var moveFrom = move.slice(0,2);
      // to: last two characters of a move
      var moveTo = move.slice(2,4);

      return [moveFrom, moveTo];
    }

    updateInfoBox(){
      // this function only gets the info currently
      var hints = ""; 

      for (var i = 0; i < this.themeList.length; i++){
        hints += "<b>" + this.ps.themesName[this.themeList[i]] + "</b>" + ": \n" + this.ps.themesDescription[this.themeList[i]]
        if (i != this.themeList.length-1){
          hints += "\n\n"
        }
      }

      var hintText = document.getElementById("hint-text");
      hintText.style.display = "none"
      hintText.innerHTML = hints;

    }

    // basic check for if a string is a fen
    isFen(fen){
      return fen.split("/").length == 8;
    }

    // shuffle array function referenced from stack overflow
    // for randomizing the puzzle array at start up so you don't always get the same order of puzzles
    shuffleArray(array) {
      for (let i = array.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [array[i], array[j]] = [array[j], array[i]];
      }
  }
}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
	<style>
        .button-container {
            position: absolute;
            top: 50%;
            right: 20px;
            transform: translateY(-50%);
        }
        .dialog-container {
            position: absolute;
            top: 50%;
        }
	    .hidden {
      	    display: none;
    	}
        .chess {
            text-align: center;
        }
        .hint {
            padding: 15px;
            display: none;
            white-space: pre-wrap;
        }
    </style>
    </head>
    <header>
        <app-header></app-header>
    </header>
    <body>
        <div class="container">
            <div id="mainElements">
                <iframe id="chessBoard" [src]="chessSrc"></iframe>

                <div id="hintMenu">

                    <div class="dialog-container">
                        <dialog id="myDialog">
                            <h1>This is a place holder header</h1>
                            <p>This is a dialog place holder text</p>
                            <button id='closeDialog'>Close</button>
                        </dialog>
                    </div>

                    <button id="newPuzzle">Get New Puzzle</button>

                    <button id='openDialog'>Show Hint</button>

                    <p id="hint-text" class="hint">Hints will show here</p>

                </div>
            </div>
        </div>		
    </body>
    <footer>
        <app-footer></app-footer>
    </footer>
</html>

// react-ystemandchess/src/features/puzzles/puzzles-page/Puzzles.tsx
import React, { useRef, useState, useEffect } from "react";
import pageStyles from "./Puzzles.module.scss";
import profileStyles from "./Puzzles-profile.module.scss";
import { Chess } from "chess.js";
import { themesName, themesDescription } from "../../../core/services/themesService";
import Swal from 'sweetalert2';
import { environment } from "../../../core/environments/environment";
import { v4 as uuidv4 } from "uuid";
import { SetPermissionLevel } from "../../../globals";
import { useCookies } from 'react-cookie'; 

const chessClientURL = environment.urls.chessClientURL;

// Global variables (keeping similar to Angular version)
let puzzleIndex = 0;
var moveList: string[] = [];
var computerColor: string;
var isPuzzleEnd = false;
var prevFEN: string;
var currentPuzzle: any;

// types for the puzzle props
type PuzzlesProps = {
  student?: any;
  mentor?: any;
  role?: any;
  styleType?: any;
};

const Puzzles: React.FC<PuzzlesProps> = ({
  student = null,
  mentor = null,
  role = "student",
  styleType = "page"
}) => {
  const styles = styleType === "profile" ? profileStyles : pageStyles;

    const chessboard = useRef<HTMLIFrameElement>(null);
    const [puzzleArray, setPuzzleArray] = useState<any[]>([]);
    const [playerMove, setPlayerMove] = useState<string[]>([]);
    const [prevMove, setPrevMove] = useState<string[]>([]);
    const [currentFen, setCurrentFen] = useState<string>('');
    const [prevFen, setPrevFen] = useState<string>('');
    const [dbIndex, setDbIndex] = useState<number>(0);
    const [info, setInfo] = useState<string>("Welcome to puzzles");
    const [playerColor, setPlayerColor] = useState<string>('');
    const [themeList, setThemeList] = useState<string[]>([]);
    const [status, setStatus] = useState<string>("");
    const swalRef = useRef<string>("");
    const [cookies] = useCookies(['login']);

    // needed for time tracking
    const [eventID, setEventID] = useState(null);
    const [startTime, setStartTime] = useState(null);
    const [username, setUsername] = useState(null);
    const handleUnloadRef = useRef(() => {});

    const postToBoard = (msg: any) => {
    const board = chessboard.current;
    if (!board || !board.contentWindow) return;

    const payload: any = { ...msg };

    if (msg.from && msg.to && !msg.nextMove) {
        const tempChess = new Chess(prevFEN);
        try {
            const moveResult = tempChess.move({
                from: msg.from,
                to: msg.to,
                promotion: 'q'
            });

            if (!moveResult) {
                console.warn("Invalid move (null):", msg);
                return;
            }

            prevFEN = tempChess.fen();
            payload.testFEN = prevFEN; // add for testing
        } catch (error) {
            console.warn("Invalid move (exception):", msg, error);
            return;
        }
    }

    board.contentWindow.postMessage(JSON.stringify(payload), chessClientURL);
  };

    // Helper: Play the next computer move from moveList, update FEN, and highlight
    const playComputerMove = () => {
      if (moveList.length === 0) return;
      const computerMove = moveList.shift();
      if (!computerMove) return;
      const moveFrom = computerMove.substring(0, 2);
      const moveTo = computerMove.substring(2, 4);

      setPrevMove([moveFrom, moveTo]); // For highlighting

      setTimeout(() => {
          // Do NOT update FEN here — let iframe do it
          // Do NOT include boardState in this message
          const chessBoard = chessboard.current;
          if (chessBoard && chessBoard.contentWindow) {
              const expectedMove = moveList[0];
            if (!expectedMove || expectedMove.length < 4) {
                console.warn("Expected move missing or invalid:", expectedMove);
                return;
            }

              chessBoard.contentWindow.postMessage(
                  JSON.stringify({
                      from: moveFrom,
                      to: moveTo,
                      nextMove: [
                          expectedMove.substring(0, 2),
                          expectedMove.substring(2, 4),
                      ],
                      computerMove: true,
                  }),
                  chessClientURL
              );
          }
      }, 300);
  };

    const setStateAsActive = (state: any) => {
        if (!state?.FEN || !state?.Moves || !state?.Themes) {
            console.warn("Puzzle is missing required fields:", state);
            return;
        }
        console.log("click state---->", state);
        // Determine which side is to move in the FEN
        const sideToMove = state.FEN.split(" ")[1];
        // Player is the opposite color
        const newPlayerColor = sideToMove === 'w' ? 'b' : 'w';
        setPlayerColor(newPlayerColor);
        

        const firstObj = {
            'theme': state.Themes,
            'fen': state.FEN,
            'event': ''
        };
        console.log("first obj---->", firstObj);

        setTimeout(() => {
            currentPuzzle = state;
            startLesson(firstObj);
        }, 200);
    };

    const startLesson = ({ theme, fen, event }: { theme: string, fen: string, event: string }) => {
        if (!fen || fen.split("/").length !== 8) {
            console.warn("Invalid or missing FEN:", fen);
            return;
        }
      setCurrentFen(fen);
      prevFEN = fen;
      
      moveList = currentPuzzle?.Moves?.split(" ") || [];
      if (moveList.length === 0) {
        console.warn("Empty or invalid moveList:", currentPuzzle);
        return;
      }

      isPuzzleEnd = false;
      setPrevMove(["", ""]);

      setTimeout(() => {
        if (!fen || fen.split(" ").length < 2 || fen.split("/").length !== 8) {
            console.warn("Invalid FEN detected before sending to iframe:", fen);
            return;
        }

        const hintText = document.getElementById("hint-text");
        if(!hintText) return;

        // 1. First send puzzle setup
        postToBoard({
            PuzzleId: currentPuzzle?.PuzzleId,
            FEN: fen,
            Moves: currentPuzzle?.Moves,
            Rating: currentPuzzle?.Rating,
            Themes: currentPuzzle?.Themes,
            Hints: hintText.innerHTML
        });

        // 2. Wait for setup, then send the first computer move if needed
        setTimeout(() => {
            // If the puzzle starts with a computer move, play it
            const tempChess = new Chess(fen);

            // First move is always by computer
            playComputerMove();

            // Otherwise, wait for player move
        }, 200);
      }, 200);
    };

    const getNextPuzzle = () => {
        if (!puzzleArray || puzzleArray.length === 0) {
            console.error("Puzzle array is empty");
            return;
        }
        console.log("getting new puzzle...");
    
        const newDbIndex = (dbIndex + 1) % puzzleArray.length;
        setDbIndex(newDbIndex);
    
        const nextPuzzle = puzzleArray[newDbIndex];
        if (!nextPuzzle.Moves) {
            console.error("Selected puzzle has no moves");
            return;
        }
    
        currentPuzzle = nextPuzzle; // Set currentPuzzle before calling setStateAsActive
        isPuzzleEnd = false;
        setPrevMove(["", ""]); // Reset prevMove for highlighting
    
        setThemeList(nextPuzzle.Themes.split(" "));
        console.log("Loading puzzle:", nextPuzzle.PuzzleId, "with FEN:", nextPuzzle.FEN);
        if (!nextPuzzle?.FEN || nextPuzzle.FEN.split("/").length !== 8) {
            console.warn("Skipping puzzle with invalid FEN:", nextPuzzle);
            return;
        }
        setStateAsActive(nextPuzzle); // This will call startLesson
        updateInfoBox(nextPuzzle.Themes.split(" "));
    };

    const isFEN = (data: string): boolean => {
        return data.split("/").length === 8;
    };

    const shuffleArray = (array: any[]) => {
        for (let i = array.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [array[i], array[j]] = [array[j], array[i]];
        }
    };

    const initPuzzleArray = async () => {
        try {
            const response = await fetch(`${environment.urls.middlewareURL}/puzzles/random?limit=20`);
            if (response.ok) {
                const jsonData = await response.json();
                setPuzzleArray(jsonData);
                return jsonData;
            } else {
                throw new Error('Failed to fetch puzzles from backend');
            }
        } catch (error) {
            console.error('Error fetching puzzles:', error);
            setPuzzleArray([]);
            return [];
        }
    };

    const prefetchPuzzles = async () => {
        try {
            const response = await fetch(`${environment.urls.middlewareURL}/puzzles/random?limit=20`);
            if (response.ok) {
                const jsonData = await response.json();
                setPuzzleArray(prev => [...prev, ...jsonData]);
            }
        } catch (error) {
            console.error('Error prefetching puzzles:', error);
        }
    };

    const updateInfoBox = (themes?: string[]) => {
      const currentThemes = themes || themeList;
      if (!currentThemes || currentThemes.length === 0) return;

      const colorDisplay = playerColor === 'w' ? 'White' : 'Black';
      const rating = currentPuzzle?.Rating || 'N/A';

      let hints = `<div style="margin-bottom: 14px;"><b>Puzzle Rating:</b> ${rating}</div>`;

      for (let i = 0; i < currentThemes.length; i++) {
        const key = currentThemes[i];
        const name = themesName[key] || key;
        const desc = themesDescription[key];

        if (!desc || desc === "No description available") continue;

        hints += `<div style="margin-bottom: 14px;"><b>${name}:</b> ${desc}</div>`;
      }

      // notify other players to also update their hints
      postToBoard({command: "message", message: hints})

      const hintText = document.getElementById("hint-text");
      if (hintText) {
        hintText.innerHTML = hints;
        hintText.style.display = "none"; // Still hidden until Show Hint clicked
      }
    }; 

    const openDialog = () => {
      const hintText = document.getElementById('hint-text');
      if (hintText) {
        hintText.style.display = hintText.style.display === "block" ? "none" : "block";
      }
    };

    // initialize component, fetch puzzles & initiate first puzzle
    const initializeComponent = async () => {
        const puzzles = await initPuzzleArray();
        if (puzzles && puzzles.length > 0) {
            setPuzzleArray(puzzles);
            // Initialize first puzzle
            const firstPuzzle = puzzles[0];
            currentPuzzle = firstPuzzle;
            moveList = firstPuzzle?.Moves?.split(" ") || [];
            if (moveList.length === 0) {
                console.warn("No valid moves in initial puzzle:", firstPuzzle);
                return;
            }

            setThemeList(firstPuzzle.Themes.split(" "));
            setStateAsActive(firstPuzzle);
            updateInfoBox(firstPuzzle.Themes.split(" "));
        }
    };

    // try joining puzzle as guest / creating puzzle as host
    const joinOrCreatePuzzle = () => {
        if(!student) student = uuidv4(); // generate random username for navBar puzzles & unlogged-in users
        if(!mentor) mentor = uuidv4();
        postToBoard({ // send student & mentor info  before server creates a game
            command: "userinfo",
            student: student,
            mentor: mentor,
            role: role
        });
        // try creating / joining, server will then notify whether user is a guest or host
        postToBoard({command: "newPuzzle"}); 
    }

    // start recording when users started browsing website
    async function startRecording() {
        const uInfo = await SetPermissionLevel(cookies); // get logged-in user info

        // do nothing if the user is not logged in
        if(uInfo.error) return;
        setUsername(uInfo.username); // else record username

        // start recording user's time spent browsing the website
        const response = await fetch(
        `${environment.urls.middlewareURL}/timeTracking/start?username=${uInfo.username}&eventType=puzzle`, 
        {
            method: 'POST',
            headers: { 'Authorization': `Bearer ${cookies.login}` }
        }
        );
        if(response.status != 200) console.log(response) // error handling

        // if data is fetched, record for later updates
        const data = await response.json();
        setEventID(data.eventId);
        setStartTime(data.startTime);
    }

    // handler called when user exist the website, complete recording time
    handleUnloadRef.current = async () => {
        try {
            const startDate = new Date(startTime)
            const endDate = new Date();
            const diffInMs = endDate.getTime() - startDate.getTime(); // time elapsed in milliseconds
            const diffInSeconds = Math.floor(diffInMs / 1000); // time elapsed in seconds

            // update the time users spent browsing website
            const response = await fetch(
                `${environment.urls.middlewareURL}/timeTracking/update?username=${username}&eventType=puzzle&eventId=${eventID}&totalTime=${diffInSeconds}`, 
                {
                    method: 'PUT',
                    headers: { 'Authorization': `Bearer ${cookies.login}` }
                }
            );
            if(response.status != 200) console.log(response) // error handling

            console.log("time spent on puzzles:", diffInSeconds);
        } catch (err) {
            console.log(err)
        }
    };

    useEffect(() => {
        startRecording();
        window.addEventListener('beforeunload', handleUnloadRef.current);

        return () => {
            window.removeEventListener('beforeunload', handleUnloadRef.current); // remove listener when unloading
            handleUnloadRef.current(); // when navigating away, stop recording time spent
        }
    }, [])
    
    useEffect(() => {
        const eventMethod = window.addEventListener ? 'addEventListener' : 'attachEvent';
        const eventer = (window as any)[eventMethod];
        const messageEvent = eventMethod === 'attachEvent' ? 'onmessage' : 'message';
    
        const messageHandler = (e: MessageEvent) => {
            let info = e.data;
            console.log('info', info);
            if (typeof info === 'string' && info[0] === "{") {
                try {
                    let jsonInfo = JSON.parse(info);
                    if (
                        "from" in jsonInfo && "to" in jsonInfo &&
                        typeof jsonInfo.from === 'string' && typeof jsonInfo.to === 'string' &&
                        jsonInfo.from.length === 2 && jsonInfo.to.length === 2
                    ) {
                        const playerAttemptedMove = `${jsonInfo.from}${jsonInfo.to}`
                        // Only allow if it's the player's turn and moveList[0] is the expected move
                        if (isPuzzleEnd || !moveList || moveList.length === 0) return;

                        const expectedPlayerMove = moveList[0]; 
                        // Now, moveList[0] is always the player's move

                        if (playerAttemptedMove === expectedPlayerMove) {
                            // Correct move
                            moveList.shift(); // Remove player's move

                            setPrevFen(currentFen);

                            if (moveList.length === 0) {
                                isPuzzleEnd = true;
                                setTimeout(() => {
                                    Swal.fire('Puzzle completed', 'Good Job', 'success').then((result) => {
                                        if(result.isConfirmed) postToBoard({command: "message", message: "next puzzle"}); // notify other players to move on to the next puzzle
                                    });
                                }, 200);
                                postToBoard({command: "message", message: "puzzle completed"}) // notify other players of the completed puzzle
                            } else {
                                // Now it's computer's turn, play the next move automatically
                                playComputerMove();
                            }
                        } else {
                            // Incorrect move, reload the puzzle
                            Swal.fire('Incorrect move', 'Try again!', 'error').then(() => {
                                startLesson({
                                    theme: currentPuzzle.Themes,
                                    fen: currentPuzzle.FEN,
                                    event: ''
                                });
                            });
                        }
                    }
                } catch (error) {
                    console.log("Error parsing JSON from iframe:", error);
                }
            } else if (info && typeof info === 'string' && isFEN(info)) {
                // FEN update from iframe (after a move)
                console.log('handling computer move', info);
                setCurrentFen(info); // Update current FEN based on board's state
                // Highlighting logic for computer's response (if prevMove is set)
                if (prevMove[0] && prevMove[1]) {
                    const chessBoard = chessboard.current;
                    if (chessBoard && chessBoard.contentWindow) {
                        chessBoard.contentWindow.postMessage(
                            JSON.stringify({
                                highlightFrom: prevMove[0],
                                highlightTo: prevMove[1]
                            }),
                            chessClientURL
                        );
                        setPrevMove(["", ""]); // Reset after highlighting
                    }
                }
            } else if (typeof info == "string" && info == "host"){ // user has created a new puzzle in server
                setStatus("host"); // change status
                initializeComponent(); 
                if (styleType === "profile") {
                    if (status){
                        if (role == "student") Swal.fire('Your mentor has left!', 'Creating a new puzzle for you', 'success');
                        else Swal.fire('Your student has left!', 'Creating a new puzzle for you', 'success');
                    } else {
                        if (role == "student") Swal.fire('You hosted a new puzzle!', 'Your mentor might join later', 'success');
                        else Swal.fire('You hosted a new puzzle!', 'Your student might join later', 'success');
                    }
                }
            } else if (typeof info == "string" && info == "guest"){ // user has joined an existing puzzle in server
                if (status == "host") {
                    if (role == "student") Swal.fire('Your mentor has joined you!', 'You can now also see their moves,', 'success');
                    else Swal.fire('Your student has joined you!', 'You can now also see their moves,', 'success');
                } else {
                    setStatus("guest"); 
                    if (role == "student") Swal.fire('You joined your mentor\'s puzzle!', 'Have fun collaborating.', 'success');
                    else Swal.fire('You joined your student\'s puzzle!', 'Have fun collaborating.', 'success');
                }
                // no need to fetch lessons, guest's chessboard is dependent on host's for simplicity
            } else if (typeof info == "string" && info == "puzzle completed" ) { // puzzle completed
                if (status == "guest") { // host would already have fired alert
                    Swal.fire('Puzzle completed', 'Good Job', 'success').then((result) => {
                        if(result.isConfirmed) postToBoard({command: "message", message: "next puzzle"}); // notify other players to move on to the next puzzle
                    });
                }
            } else if (typeof info == "string" && info == "next puzzle") { // player / other users want to move to the next puzzle
                Swal.close();
                if(status == "guest"){
                    Swal.fire({
                        title: 'Loading next lesson',
                        text: 'Please wait...',
                        allowOutsideClick: false,
                        allowEscapeKey: false,
                        showConfirmButton: false,
                        didOpen: () => {
                            Swal.showLoading();
                            swalRef.current = "loading";
                        },
                        willClose: () => {
                            swalRef.current = "";
                        }
                    });
                }
                getNextPuzzle();
            } else if (typeof info == "string" && info.startsWith("<div")) { // other users want to update the hint text
                if(status == "guest") { // host initiates, only guests receive
                    const hintText = document.getElementById("hint-text");
                    if (hintText) {
                        hintText.innerHTML = info;
                        hintText.style.display = "none"; // Still hidden until Show Hint clicked
                    }
                }
            } else if (typeof info == "string" && info == "new game received") {
                if(swalRef.current == "loading") Swal.close();
            }
        };
    
        eventer(messageEvent, messageHandler, false);
    
        return () => {
            const cleanupEventer = (window as any)[window.removeEventListener ? 'removeEventListener' : 'detachEvent'];
            const cleanupMessageEvent = window.removeEventListener ? 'message' : 'onmessage';
            cleanupEventer(cleanupMessageEvent, messageHandler, false);
        };
    }, [currentFen, prevFen, playerColor, puzzleArray, currentPuzzle, isPuzzleEnd, prevMove, status]);

    return (
    <div className={styles.mainElements}>
        <iframe
        onLoad={joinOrCreatePuzzle}
        ref={chessboard}
        className={styles.chessBoard}
        src={chessClientURL}
        title="board"
        id="chessBoard"
        />
        <div className={styles.hintMenu}>
        <div className={styles.hintButtonRow}>
            <button
            className={styles.puzzleButton}
            onClick={() => {
                isPuzzleEnd = false;
                postToBoard({command: "message", message: "next puzzle"});
            }}
            >
            Get New Puzzle
            </button>

            <button className={styles.puzzleButton} onClick={openDialog}>
            Show Hint
            </button>
        </div>
        <div
            id="hint-text"
            className={styles.hintText}
            style={{ display: 'none' }}
        ></div>
        </div>
    </div>
    );


}

export default Puzzles;
